//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ork.Waste.DeleteEvaluationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeleteEvaluationService.DeleteEvaluationService")]
    public interface DeleteEvaluationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEvaluationService/CanDelete", ReplyAction="http://tempuri.org/DeleteEvaluationService/CanDeleteResponse")]
        bool CanDelete(string type, int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEvaluationService/CanDelete", ReplyAction="http://tempuri.org/DeleteEvaluationService/CanDeleteResponse")]
        System.Threading.Tasks.Task<bool> CanDeleteAsync(string type, int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeleteEvaluationServiceChannel : Ork.Waste.DeleteEvaluationService.DeleteEvaluationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteEvaluationServiceClient : System.ServiceModel.ClientBase<Ork.Waste.DeleteEvaluationService.DeleteEvaluationService>, Ork.Waste.DeleteEvaluationService.DeleteEvaluationService {
        
        public DeleteEvaluationServiceClient() {
        }
        
        public DeleteEvaluationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeleteEvaluationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteEvaluationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeleteEvaluationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CanDelete(string type, int id) {
            return base.Channel.CanDelete(type, id);
        }
        
        public System.Threading.Tasks.Task<bool> CanDeleteAsync(string type, int id) {
            return base.Channel.CanDeleteAsync(type, id);
        }
    }
}
