//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ork.Danger.SurveyParserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SurveyParserService.SurveyParserService")]
    public interface SurveyParserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SurveyParserService/GenerateSurvey", ReplyAction="http://tempuri.org/SurveyParserService/GenerateSurveyResponse")]
        void GenerateSurvey(int surveyTypeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SurveyParserService/GenerateSurvey", ReplyAction="http://tempuri.org/SurveyParserService/GenerateSurveyResponse")]
        System.Threading.Tasks.Task GenerateSurveyAsync(int surveyTypeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SurveyParserServiceChannel : Ork.Danger.SurveyParserService.SurveyParserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SurveyParserServiceClient : System.ServiceModel.ClientBase<Ork.Danger.SurveyParserService.SurveyParserService>, Ork.Danger.SurveyParserService.SurveyParserService {
        
        public SurveyParserServiceClient() {
        }
        
        public SurveyParserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SurveyParserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyParserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyParserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GenerateSurvey(int surveyTypeId) {
            base.Channel.GenerateSurvey(surveyTypeId);
        }
        
        public System.Threading.Tasks.Task GenerateSurveyAsync(int surveyTypeId) {
            return base.Channel.GenerateSurveyAsync(surveyTypeId);
        }
    }
}
