//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 09.12.2013 11:03:54
namespace Ork.Meter.DomainModelService
{
    
    /// <summary>
    /// There are no comments for DomainModelContext in the schema.
    /// </summary>
    public partial class DomainModelContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DomainModelContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DomainModelContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "OpenResKit.DomainModel", "Ork.Meter.DomainModelService");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Ork.Meter.DomainModelService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OpenResKit.DomainModel.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Meters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Meter> Meters
        {
            get
            {
                if ((this._Meters == null))
                {
                    this._Meters = base.CreateQuery<Meter>("Meters");
                }
                return this._Meters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Meter> _Meters;
        /// <summary>
        /// There are no comments for MapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MapPosition> MapPositions
        {
            get
            {
                if ((this._MapPositions == null))
                {
                    this._MapPositions = base.CreateQuery<MapPosition>("MapPositions");
                }
                return this._MapPositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MapPosition> _MapPositions;
        /// <summary>
        /// There are no comments for Maps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Map> Maps
        {
            get
            {
                if ((this._Maps == null))
                {
                    this._Maps = base.CreateQuery<Map>("Maps");
                }
                return this._Maps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Map> _Maps;
        /// <summary>
        /// There are no comments for MapSources in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MapSource> MapSources
        {
            get
            {
                if ((this._MapSources == null))
                {
                    this._MapSources = base.CreateQuery<MapSource>("MapSources");
                }
                return this._MapSources;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MapSource> _MapSources;
        /// <summary>
        /// There are no comments for ResponsibleSubjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ResponsibleSubject> ResponsibleSubjects
        {
            get
            {
                if ((this._ResponsibleSubjects == null))
                {
                    this._ResponsibleSubjects = base.CreateQuery<ResponsibleSubject>("ResponsibleSubjects");
                }
                return this._ResponsibleSubjects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ResponsibleSubject> _ResponsibleSubjects;
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Appointment> Appointments
        {
            get
            {
                if ((this._Appointments == null))
                {
                    this._Appointments = base.CreateQuery<Appointment>("Appointments");
                }
                return this._Appointments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Appointment> _Appointments;
        /// <summary>
        /// There are no comments for Series in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Series> Series
        {
            get
            {
                if ((this._Series == null))
                {
                    this._Series = base.CreateQuery<Series>("Series");
                }
                return this._Series;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Series> _Series;
        /// <summary>
        /// There are no comments for SeriesColors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<SeriesColor> SeriesColors
        {
            get
            {
                if ((this._SeriesColors == null))
                {
                    this._SeriesColors = base.CreateQuery<SeriesColor>("SeriesColors");
                }
                return this._SeriesColors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<SeriesColor> _SeriesColors;
        /// <summary>
        /// There are no comments for DayOfWeeks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DayOfWeek> DayOfWeeks
        {
            get
            {
                if ((this._DayOfWeeks == null))
                {
                    this._DayOfWeeks = base.CreateQuery<DayOfWeek>("DayOfWeeks");
                }
                return this._DayOfWeeks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DayOfWeek> _DayOfWeeks;
        /// <summary>
        /// There are no comments for ScheduledTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ScheduledTask> ScheduledTasks
        {
            get
            {
                if ((this._ScheduledTasks == null))
                {
                    this._ScheduledTasks = base.CreateQuery<ScheduledTask>("ScheduledTasks/OpenResKit.DomainModel.MeterReading");
                }
                return this._ScheduledTasks;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ScheduledTask> _ScheduledTasks;
        /// <summary>
        /// There are no comments for Meters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeters(Meter meter)
        {
            base.AddObject("Meters", meter);
        }
        /// <summary>
        /// There are no comments for MapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMapPositions(MapPosition mapPosition)
        {
            base.AddObject("MapPositions", mapPosition);
        }
        /// <summary>
        /// There are no comments for Maps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMaps(Map map)
        {
            base.AddObject("Maps", map);
        }
        /// <summary>
        /// There are no comments for MapSources in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMapSources(MapSource mapSource)
        {
            base.AddObject("MapSources", mapSource);
        }
        /// <summary>
        /// There are no comments for ResponsibleSubjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToResponsibleSubjects(ResponsibleSubject responsibleSubject)
        {
            base.AddObject("ResponsibleSubjects", responsibleSubject);
        }
        /// <summary>
        /// There are no comments for Appointments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAppointments(Appointment appointment)
        {
            base.AddObject("Appointments", appointment);
        }
        /// <summary>
        /// There are no comments for Series in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSeries(Series series)
        {
            base.AddObject("Series", series);
        }
        /// <summary>
        /// There are no comments for SeriesColors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSeriesColors(SeriesColor seriesColor)
        {
            base.AddObject("SeriesColors", seriesColor);
        }
        /// <summary>
        /// There are no comments for DayOfWeeks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDayOfWeeks(DayOfWeek dayOfWeek)
        {
            base.AddObject("DayOfWeeks", dayOfWeek);
        }
        /// <summary>
        /// There are no comments for ScheduledTasks in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToScheduledTasks(ScheduledTask scheduledTask)
        {
            base.AddObject("ScheduledTasks", scheduledTask);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"OpenResKit.DomainModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/" +
                "11/edm\"><EntityType Name=\"Meter\"><Key><PropertyRef Name=\"Id\" /></Key><Property N" +
                "ame=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" x" +
                "mlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Na" +
                "me=\"Barcode\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true" +
                "\" /><Property Name=\"Number\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false" +
                "\" Unicode=\"true\" /><Property Name=\"Unit\" Type=\"Edm.String\" MaxLength=\"Max\" Fixed" +
                "Length=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"MapPosition\" Relations" +
                "hip=\"OpenResKit.DomainModel.Meter_MapPosition\" ToRole=\"Meter_MapPosition_Target\"" +
                " FromRole=\"Meter_MapPosition_Source\" /></EntityType><EntityType Name=\"MapPositio" +
                "n\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Null" +
                "able=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.micros" +
                "oft.com/ado/2009/02/edm/annotation\" /><Property Name=\"XPosition\" Type=\"Edm.Doubl" +
                "e\" Nullable=\"false\" /><Property Name=\"YPosition\" Type=\"Edm.Double\" Nullable=\"fal" +
                "se\" /><NavigationProperty Name=\"Map\" Relationship=\"OpenResKit.DomainModel.MapPos" +
                "ition_Map\" ToRole=\"MapPosition_Map_Target\" FromRole=\"MapPosition_Map_Source\" /><" +
                "/EntityType><EntityType Name=\"Map\"><Key><PropertyRef Name=\"Id\" /></Key><Property" +
                " Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\"" +
                " xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property " +
                "Name=\"Name\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\"" +
                " /><NavigationProperty Name=\"MapSource\" Relationship=\"OpenResKit.DomainModel.Map" +
                "_MapSource\" ToRole=\"Map_MapSource_Target\" FromRole=\"Map_MapSource_Source\" /></En" +
                "tityType><EntityType Name=\"MapSource\"><Key><PropertyRef Name=\"Id\" /></Key><Prope" +
                "rty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identi" +
                "ty\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Proper" +
                "ty Name=\"BinarySource\" Type=\"Edm.Binary\" MaxLength=\"Max\" FixedLength=\"false\" /><" +
                "/EntityType><EntityType Name=\"ResponsibleSubject\" Abstract=\"true\"><Key><Property" +
                "Ref Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:S" +
                "toreGeneratedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/" +
                "02/edm/annotation\" /></EntityType><EntityType Name=\"Employee\" BaseType=\"OpenResK" +
                "it.DomainModel.ResponsibleSubject\"><Property Name=\"FirstName\" Type=\"Edm.String\" " +
                "MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"LastName\" T" +
                "ype=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property " +
                "Name=\"UserName\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"t" +
                "rue\" /><Property Name=\"Number\" Type=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"fa" +
                "lse\" Unicode=\"true\" /><NavigationProperty Name=\"Groups\" Relationship=\"OpenResKit" +
                ".DomainModel.Employee_Groups\" ToRole=\"Employee_Groups_Target\" FromRole=\"Employee" +
                "_Groups_Source\" /></EntityType><EntityType Name=\"EmployeeGroup\" BaseType=\"OpenRe" +
                "sKit.DomainModel.ResponsibleSubject\"><Property Name=\"Name\" Type=\"Edm.String\" Max" +
                "Length=\"Max\" FixedLength=\"false\" Unicode=\"true\" /></EntityType><EntityType Name=" +
                "\"Appointment\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm." +
                "Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" xmlns:p6=\"http://sch" +
                "emas.microsoft.com/ado/2009/02/edm/annotation\" /><Property Name=\"Begin\" Type=\"Ed" +
                "m.DateTime\" Nullable=\"false\" /><Property Name=\"End\" Type=\"Edm.DateTime\" Nullable" +
                "=\"false\" /><Property Name=\"IsAllDay\" Type=\"Edm.Boolean\" Nullable=\"false\" /></Ent" +
                "ityType><EntityType Name=\"Series\"><Key><PropertyRef Name=\"Id\" /></Key><Property " +
                "Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=\"Identity\" " +
                "xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" /><Property N" +
                "ame=\"Begin\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"Cycle\" Type=\"" +
                "Edm.Int32\" Nullable=\"false\" /><Property Name=\"End\" Type=\"Edm.DateTime\" Nullable=" +
                "\"false\" /><Property Name=\"EndsWithDate\" Type=\"Edm.Boolean\" Nullable=\"false\" /><P" +
                "roperty Name=\"IsAllDay\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Is" +
                "WeekdayRecurrence\" Type=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"Name\" T" +
                "ype=\"Edm.String\" MaxLength=\"Max\" FixedLength=\"false\" Unicode=\"true\" /><Property " +
                "Name=\"NumberOfRecurrences\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"R" +
                "ecurrenceInterval\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Repeat\" T" +
                "ype=\"Edm.Boolean\" Nullable=\"false\" /><Property Name=\"RepeatUntilDate\" Type=\"Edm." +
                "DateTime\" Nullable=\"false\" /><NavigationProperty Name=\"SeriesColor\" Relationship" +
                "=\"OpenResKit.DomainModel.Series_SeriesColor\" ToRole=\"Series_SeriesColor_Target\" " +
                "FromRole=\"Series_SeriesColor_Source\" /><NavigationProperty Name=\"WeekDays\" Relat" +
                "ionship=\"OpenResKit.DomainModel.Series_WeekDays\" ToRole=\"Series_WeekDays_Target\"" +
                " FromRole=\"Series_WeekDays_Source\" /></EntityType><EntityType Name=\"SeriesColor\"" +
                "><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullab" +
                "le=\"false\" /><Property Name=\"B\" Type=\"Edm.Byte\" Nullable=\"false\" /><Property Nam" +
                "e=\"G\" Type=\"Edm.Byte\" Nullable=\"false\" /><Property Name=\"R\" Type=\"Edm.Byte\" Null" +
                "able=\"false\" /></EntityType><EntityType Name=\"DayOfWeek\"><Key><PropertyRef Name=" +
                "\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGener" +
                "atedPattern=\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/an" +
                "notation\" /><Property Name=\"WeekDay\" Type=\"Edm.Int32\" Nullable=\"false\" /></Entit" +
                "yType><EntityType Name=\"ScheduledTask\"><Key><PropertyRef Name=\"Id\" /></Key><Prop" +
                "erty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Progress\" Typ" +
                "e=\"Edm.Single\" Nullable=\"false\" /><NavigationProperty Name=\"AppointmentResponsib" +
                "leSubject\" Relationship=\"OpenResKit.DomainModel.ScheduledTask_AppointmentRespons" +
                "ibleSubject\" ToRole=\"ScheduledTask_AppointmentResponsibleSubject_Target\" FromRol" +
                "e=\"ScheduledTask_AppointmentResponsibleSubject_Source\" /><NavigationProperty Nam" +
                "e=\"DueDate\" Relationship=\"OpenResKit.DomainModel.ScheduledTask_DueDate\" ToRole=\"" +
                "ScheduledTask_DueDate_Target\" FromRole=\"ScheduledTask_DueDate_Source\" /><Navigat" +
                "ionProperty Name=\"EntryDate\" Relationship=\"OpenResKit.DomainModel.ScheduledTask_" +
                "EntryDate\" ToRole=\"ScheduledTask_EntryDate_Target\" FromRole=\"ScheduledTask_Entry" +
                "Date_Source\" /><NavigationProperty Name=\"EntryResponsibleSubject\" Relationship=\"" +
                "OpenResKit.DomainModel.ScheduledTask_EntryResponsibleSubject\" ToRole=\"ScheduledT" +
                "ask_EntryResponsibleSubject_Target\" FromRole=\"ScheduledTask_EntryResponsibleSubj" +
                "ect_Source\" /><NavigationProperty Name=\"RelatedSeries\" Relationship=\"OpenResKit." +
                "DomainModel.ScheduledTask_RelatedSeries\" ToRole=\"ScheduledTask_RelatedSeries_Tar" +
                "get\" FromRole=\"ScheduledTask_RelatedSeries_Source\" /></EntityType><EntityType Na" +
                "me=\"MeterReading\" BaseType=\"OpenResKit.DomainModel.ScheduledTask\"><Property Name" +
                "=\"CounterReading\" Type=\"Edm.Double\" Nullable=\"false\" /><NavigationProperty Name=" +
                "\"ReadingMeter\" Relationship=\"OpenResKit.DomainModel.MeterReading_ReadingMeter\" T" +
                "oRole=\"MeterReading_ReadingMeter_Target\" FromRole=\"MeterReading_ReadingMeter_Sou" +
                "rce\" /></EntityType><Association Name=\"Meter_MapPosition\"><End Type=\"OpenResKit." +
                "DomainModel.MapPosition\" Role=\"Meter_MapPosition_Target\" Mu";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "ltiplicity=\"0..1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"OpenResKit.Domain" +
                "Model.Meter\" Role=\"Meter_MapPosition_Source\" Multiplicity=\"0..1\" /></Association" +
                "><Association Name=\"MapPosition_Map\"><End Type=\"OpenResKit.DomainModel.Map\" Role" +
                "=\"MapPosition_Map_Target\" Multiplicity=\"0..1\" /><End Type=\"OpenResKit.DomainMode" +
                "l.MapPosition\" Role=\"MapPosition_Map_Source\" Multiplicity=\"*\" /></Association><A" +
                "ssociation Name=\"Map_MapSource\"><End Type=\"OpenResKit.DomainModel.MapSource\" Rol" +
                "e=\"Map_MapSource_Target\" Multiplicity=\"0..1\" /><End Type=\"OpenResKit.DomainModel" +
                ".Map\" Role=\"Map_MapSource_Source\" Multiplicity=\"*\" /></Association><Association " +
                "Name=\"Employee_Groups\"><End Type=\"OpenResKit.DomainModel.Employee\" Role=\"Employe" +
                "e_Groups_Source\" Multiplicity=\"*\" /><End Type=\"OpenResKit.DomainModel.EmployeeGr" +
                "oup\" Role=\"Employee_Groups_Target\" Multiplicity=\"*\" /></Association><Association" +
                " Name=\"Series_SeriesColor\"><End Type=\"OpenResKit.DomainModel.Series\" Role=\"Serie" +
                "s_SeriesColor_Source\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End T" +
                "ype=\"OpenResKit.DomainModel.SeriesColor\" Role=\"Series_SeriesColor_Target\" Multip" +
                "licity=\"1\" /><ReferentialConstraint><Principal Role=\"Series_SeriesColor_Source\">" +
                "<PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"Series_SeriesColor_Target\"" +
                "><PropertyRef Name=\"Id\" /></Dependent></ReferentialConstraint></Association><Ass" +
                "ociation Name=\"Series_WeekDays\"><End Type=\"OpenResKit.DomainModel.Series\" Role=\"" +
                "Series_WeekDays_Source\" Multiplicity=\"0..1\"><OnDelete Action=\"Cascade\" /></End><" +
                "End Type=\"OpenResKit.DomainModel.DayOfWeek\" Role=\"Series_WeekDays_Target\" Multip" +
                "licity=\"*\" /></Association><Association Name=\"ScheduledTask_AppointmentResponsib" +
                "leSubject\"><End Type=\"OpenResKit.DomainModel.ResponsibleSubject\" Role=\"Scheduled" +
                "Task_AppointmentResponsibleSubject_Target\" Multiplicity=\"0..1\" /><End Type=\"Open" +
                "ResKit.DomainModel.ScheduledTask\" Role=\"ScheduledTask_AppointmentResponsibleSubj" +
                "ect_Source\" Multiplicity=\"*\" /></Association><Association Name=\"ScheduledTask_Du" +
                "eDate\"><End Type=\"OpenResKit.DomainModel.Appointment\" Role=\"ScheduledTask_DueDat" +
                "e_Target\" Multiplicity=\"1\"><OnDelete Action=\"Cascade\" /></End><End Type=\"OpenRes" +
                "Kit.DomainModel.ScheduledTask\" Role=\"ScheduledTask_DueDate_Source\" Multiplicity=" +
                "\"0..1\" /><ReferentialConstraint><Principal Role=\"ScheduledTask_DueDate_Target\"><" +
                "PropertyRef Name=\"Id\" /></Principal><Dependent Role=\"ScheduledTask_DueDate_Sourc" +
                "e\"><PropertyRef Name=\"Id\" /></Dependent></ReferentialConstraint></Association><A" +
                "ssociation Name=\"ScheduledTask_EntryDate\"><End Type=\"OpenResKit.DomainModel.Appo" +
                "intment\" Role=\"ScheduledTask_EntryDate_Target\" Multiplicity=\"0..1\" /><End Type=\"" +
                "OpenResKit.DomainModel.ScheduledTask\" Role=\"ScheduledTask_EntryDate_Source\" Mult" +
                "iplicity=\"*\" /></Association><Association Name=\"ScheduledTask_EntryResponsibleSu" +
                "bject\"><End Type=\"OpenResKit.DomainModel.ResponsibleSubject\" Role=\"ScheduledTask" +
                "_EntryResponsibleSubject_Target\" Multiplicity=\"0..1\" /><End Type=\"OpenResKit.Dom" +
                "ainModel.ScheduledTask\" Role=\"ScheduledTask_EntryResponsibleSubject_Source\" Mult" +
                "iplicity=\"*\" /></Association><Association Name=\"ScheduledTask_RelatedSeries\"><En" +
                "d Type=\"OpenResKit.DomainModel.Series\" Role=\"ScheduledTask_RelatedSeries_Target\"" +
                " Multiplicity=\"0..1\" /><End Type=\"OpenResKit.DomainModel.ScheduledTask\" Role=\"Sc" +
                "heduledTask_RelatedSeries_Source\" Multiplicity=\"*\" /></Association><Association " +
                "Name=\"MeterReading_ReadingMeter\"><End Type=\"OpenResKit.DomainModel.MeterReading\"" +
                " Role=\"MeterReading_ReadingMeter_Source\" Multiplicity=\"*\" /><End Type=\"OpenResKi" +
                "t.DomainModel.Meter\" Role=\"MeterReading_ReadingMeter_Target\" Multiplicity=\"0..1\"" +
                " /></Association><EntityContainer Name=\"DomainModelContext\" m:IsDefaultEntityCon" +
                "tainer=\"true\"><EntitySet Name=\"Meters\" EntityType=\"OpenResKit.DomainModel.Meter\"" +
                " /><EntitySet Name=\"MapPositions\" EntityType=\"OpenResKit.DomainModel.MapPosition" +
                "\" /><EntitySet Name=\"Maps\" EntityType=\"OpenResKit.DomainModel.Map\" /><EntitySet " +
                "Name=\"MapSources\" EntityType=\"OpenResKit.DomainModel.MapSource\" /><EntitySet Nam" +
                "e=\"ResponsibleSubjects\" EntityType=\"OpenResKit.DomainModel.ResponsibleSubject\" /" +
                "><EntitySet Name=\"Appointments\" EntityType=\"OpenResKit.DomainModel.Appointment\" " +
                "/><EntitySet Name=\"Series\" EntityType=\"OpenResKit.DomainModel.Series\" /><EntityS" +
                "et Name=\"SeriesColors\" EntityType=\"OpenResKit.DomainModel.SeriesColor\" /><Entity" +
                "Set Name=\"DayOfWeeks\" EntityType=\"OpenResKit.DomainModel.DayOfWeek\" /><EntitySet" +
                " Name=\"ScheduledTasks\" EntityType=\"OpenResKit.DomainModel.ScheduledTask\" /><Asso" +
                "ciationSet Name=\"Meter_MapPosition\" Association=\"OpenResKit.DomainModel.Meter_Ma" +
                "pPosition\"><End Role=\"Meter_MapPosition_Source\" EntitySet=\"Meters\" /><End Role=\"" +
                "Meter_MapPosition_Target\" EntitySet=\"MapPositions\" /></AssociationSet><Associati" +
                "onSet Name=\"MapPosition_Map\" Association=\"OpenResKit.DomainModel.MapPosition_Map" +
                "\"><End Role=\"MapPosition_Map_Source\" EntitySet=\"MapPositions\" /><End Role=\"MapPo" +
                "sition_Map_Target\" EntitySet=\"Maps\" /></AssociationSet><AssociationSet Name=\"Map" +
                "_MapSource\" Association=\"OpenResKit.DomainModel.Map_MapSource\"><End Role=\"Map_Ma" +
                "pSource_Source\" EntitySet=\"Maps\" /><End Role=\"Map_MapSource_Target\" EntitySet=\"M" +
                "apSources\" /></AssociationSet><AssociationSet Name=\"Employee_Groups\" Association" +
                "=\"OpenResKit.DomainModel.Employee_Groups\"><End Role=\"Employee_Groups_Source\" Ent" +
                "itySet=\"ResponsibleSubjects\" /><End Role=\"Employee_Groups_Target\" EntitySet=\"Res" +
                "ponsibleSubjects\" /></AssociationSet><AssociationSet Name=\"Series_SeriesColor\" A" +
                "ssociation=\"OpenResKit.DomainModel.Series_SeriesColor\"><End Role=\"Series_SeriesC" +
                "olor_Source\" EntitySet=\"Series\" /><End Role=\"Series_SeriesColor_Target\" EntitySe" +
                "t=\"SeriesColors\" /></AssociationSet><AssociationSet Name=\"Series_WeekDays\" Assoc" +
                "iation=\"OpenResKit.DomainModel.Series_WeekDays\"><End Role=\"Series_WeekDays_Sourc" +
                "e\" EntitySet=\"Series\" /><End Role=\"Series_WeekDays_Target\" EntitySet=\"DayOfWeeks" +
                "\" /></AssociationSet><AssociationSet Name=\"MeterReading_ReadingMeter\" Associatio" +
                "n=\"OpenResKit.DomainModel.MeterReading_ReadingMeter\"><End Role=\"MeterReading_Rea" +
                "dingMeter_Source\" EntitySet=\"ScheduledTasks\" /><End Role=\"MeterReading_ReadingMe" +
                "ter_Target\" EntitySet=\"Meters\" /></AssociationSet><AssociationSet Name=\"Schedule" +
                "dTask_AppointmentResponsibleSubject\" Association=\"OpenResKit.DomainModel.Schedul" +
                "edTask_AppointmentResponsibleSubject\"><End Role=\"ScheduledTask_AppointmentRespon" +
                "sibleSubject_Source\" EntitySet=\"ScheduledTasks\" /><End Role=\"ScheduledTask_Appoi" +
                "ntmentResponsibleSubject_Target\" EntitySet=\"ResponsibleSubjects\" /></Association" +
                "Set><AssociationSet Name=\"ScheduledTask_DueDate\" Association=\"OpenResKit.DomainM" +
                "odel.ScheduledTask_DueDate\"><End Role=\"ScheduledTask_DueDate_Source\" EntitySet=\"" +
                "ScheduledTasks\" /><End Role=\"ScheduledTask_DueDate_Target\" EntitySet=\"Appointmen" +
                "ts\" /></AssociationSet><AssociationSet Name=\"ScheduledTask_EntryDate\" Associatio" +
                "n=\"OpenResKit.DomainModel.ScheduledTask_EntryDate\"><End Role=\"ScheduledTask_Entr" +
                "yDate_Source\" EntitySet=\"ScheduledTasks\" /><End Role=\"ScheduledTask_EntryDate_Ta" +
                "rget\" EntitySet=\"Appointments\" /></AssociationSet><AssociationSet Name=\"Schedule" +
                "dTask_EntryResponsibleSubject\" Association=\"OpenResKit.DomainModel.ScheduledTask" +
                "_EntryResponsibleSubject\"><End Role=\"ScheduledTask_EntryResponsibleSubject_Sourc" +
                "e\" EntitySet=\"ScheduledTasks\" /><End Role=\"ScheduledTask_EntryResponsibleSubject" +
                "_Target\" EntitySet=\"ResponsibleSubjects\" /></AssociationSet><AssociationSet Name" +
                "=\"ScheduledTask_RelatedSeries\" Association=\"OpenResKit.DomainModel.ScheduledTask" +
                "_RelatedSeries\"><End Role=\"ScheduledTask_RelatedSeries_Sour";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart2 = "ce\" EntitySet=\"ScheduledTasks\" /><End Role=\"ScheduledTask_RelatedSeries_Target\" E" +
                "ntitySet=\"Series\" /></AssociationSet></EntityContainer></Schema></edmx:DataServi" +
                "ces></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1, ModelPart2);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Meter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Meters")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Meter : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Meter object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Meter CreateMeter(int ID)
        {
            Meter meter = new Meter();
            meter.Id = ID;
            return meter;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Barcode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Barcode
        {
            get
            {
                return this._Barcode;
            }
            set
            {
                this.OnBarcodeChanging(value);
                this._Barcode = value;
                this.OnBarcodeChanged();
                this.OnPropertyChanged("Barcode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Barcode;
        partial void OnBarcodeChanging(string value);
        partial void OnBarcodeChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Unit
        {
            get
            {
                return this._Unit;
            }
            set
            {
                this.OnUnitChanging(value);
                this._Unit = value;
                this.OnUnitChanged();
                this.OnPropertyChanged("Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Unit;
        partial void OnUnitChanging(string value);
        partial void OnUnitChanged();
        /// <summary>
        /// There are no comments for MapPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MapPosition MapPosition
        {
            get
            {
                return this._MapPosition;
            }
            set
            {
                this._MapPosition = value;
                this.OnPropertyChanged("MapPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MapPosition _MapPosition;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MapPosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MapPositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MapPosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MapPosition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="xPosition">Initial value of XPosition.</param>
        /// <param name="yPosition">Initial value of YPosition.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MapPosition CreateMapPosition(int ID, double xPosition, double yPosition)
        {
            MapPosition mapPosition = new MapPosition();
            mapPosition.Id = ID;
            mapPosition.XPosition = xPosition;
            mapPosition.YPosition = yPosition;
            return mapPosition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property XPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double XPosition
        {
            get
            {
                return this._XPosition;
            }
            set
            {
                this.OnXPositionChanging(value);
                this._XPosition = value;
                this.OnXPositionChanged();
                this.OnPropertyChanged("XPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _XPosition;
        partial void OnXPositionChanging(double value);
        partial void OnXPositionChanged();
        /// <summary>
        /// There are no comments for Property YPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double YPosition
        {
            get
            {
                return this._YPosition;
            }
            set
            {
                this.OnYPositionChanging(value);
                this._YPosition = value;
                this.OnYPositionChanged();
                this.OnPropertyChanged("YPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _YPosition;
        partial void OnYPositionChanging(double value);
        partial void OnYPositionChanged();
        /// <summary>
        /// There are no comments for Map in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Map Map
        {
            get
            {
                return this._Map;
            }
            set
            {
                this._Map = value;
                this.OnPropertyChanged("Map");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Map _Map;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Map in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Maps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Map : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Map object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Map CreateMap(int ID)
        {
            Map map = new Map();
            map.Id = ID;
            return map;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for MapSource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MapSource MapSource
        {
            get
            {
                return this._MapSource;
            }
            set
            {
                this._MapSource = value;
                this.OnPropertyChanged("MapSource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MapSource _MapSource;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MapSource in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MapSources")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MapSource : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MapSource object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MapSource CreateMapSource(int ID)
        {
            MapSource mapSource = new MapSource();
            mapSource.Id = ID;
            return mapSource;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property BinarySource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] BinarySource
        {
            get
            {
                if ((this._BinarySource != null))
                {
                    return ((byte[])(this._BinarySource.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnBinarySourceChanging(value);
                this._BinarySource = value;
                this.OnBinarySourceChanged();
                this.OnPropertyChanged("BinarySource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _BinarySource;
        partial void OnBinarySourceChanging(byte[] value);
        partial void OnBinarySourceChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.ResponsibleSubject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ResponsibleSubjects")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public abstract partial class ResponsibleSubject : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Employee : ResponsibleSubject
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Employee CreateEmployee(int ID)
        {
            Employee employee = new Employee();
            employee.Id = ID;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup> Groups
        {
            get
            {
                return this._Groups;
            }
            set
            {
                this._Groups = value;
                this.OnPropertyChanged("Groups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup> _Groups = new global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup>(null, global::System.Data.Services.Client.TrackingMode.None);
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.EmployeeGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EmployeeGroup : ResponsibleSubject
    {
        /// <summary>
        /// Create a new EmployeeGroup object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EmployeeGroup CreateEmployeeGroup(int ID)
        {
            EmployeeGroup employeeGroup = new EmployeeGroup();
            employeeGroup.Id = ID;
            return employeeGroup;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Appointment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Appointments")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Appointment : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Appointment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="begin">Initial value of Begin.</param>
        /// <param name="end">Initial value of End.</param>
        /// <param name="isAllDay">Initial value of IsAllDay.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Appointment CreateAppointment(int ID, global::System.DateTime begin, global::System.DateTime end, bool isAllDay)
        {
            Appointment appointment = new Appointment();
            appointment.Id = ID;
            appointment.Begin = begin;
            appointment.End = end;
            appointment.IsAllDay = isAllDay;
            return appointment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Begin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Begin
        {
            get
            {
                return this._Begin;
            }
            set
            {
                this.OnBeginChanging(value);
                this._Begin = value;
                this.OnBeginChanged();
                this.OnPropertyChanged("Begin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Begin;
        partial void OnBeginChanging(global::System.DateTime value);
        partial void OnBeginChanged();
        /// <summary>
        /// There are no comments for Property End in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime End
        {
            get
            {
                return this._End;
            }
            set
            {
                this.OnEndChanging(value);
                this._End = value;
                this.OnEndChanged();
                this.OnPropertyChanged("End");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
        /// <summary>
        /// There are no comments for Property IsAllDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAllDay
        {
            get
            {
                return this._IsAllDay;
            }
            set
            {
                this.OnIsAllDayChanging(value);
                this._IsAllDay = value;
                this.OnIsAllDayChanged();
                this.OnPropertyChanged("IsAllDay");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAllDay;
        partial void OnIsAllDayChanging(bool value);
        partial void OnIsAllDayChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Series in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Series")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Series : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Series object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="begin">Initial value of Begin.</param>
        /// <param name="cycle">Initial value of Cycle.</param>
        /// <param name="end">Initial value of End.</param>
        /// <param name="endsWithDate">Initial value of EndsWithDate.</param>
        /// <param name="isAllDay">Initial value of IsAllDay.</param>
        /// <param name="isWeekdayRecurrence">Initial value of IsWeekdayRecurrence.</param>
        /// <param name="numberOfRecurrences">Initial value of NumberOfRecurrences.</param>
        /// <param name="recurrenceInterval">Initial value of RecurrenceInterval.</param>
        /// <param name="repeat">Initial value of Repeat.</param>
        /// <param name="repeatUntilDate">Initial value of RepeatUntilDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Series CreateSeries(int ID, global::System.DateTime begin, int cycle, global::System.DateTime end, bool endsWithDate, bool isAllDay, bool isWeekdayRecurrence, int numberOfRecurrences, int recurrenceInterval, bool repeat, global::System.DateTime repeatUntilDate)
        {
            Series series = new Series();
            series.Id = ID;
            series.Begin = begin;
            series.Cycle = cycle;
            series.End = end;
            series.EndsWithDate = endsWithDate;
            series.IsAllDay = isAllDay;
            series.IsWeekdayRecurrence = isWeekdayRecurrence;
            series.NumberOfRecurrences = numberOfRecurrences;
            series.RecurrenceInterval = recurrenceInterval;
            series.Repeat = repeat;
            series.RepeatUntilDate = repeatUntilDate;
            return series;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Begin in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Begin
        {
            get
            {
                return this._Begin;
            }
            set
            {
                this.OnBeginChanging(value);
                this._Begin = value;
                this.OnBeginChanged();
                this.OnPropertyChanged("Begin");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Begin;
        partial void OnBeginChanging(global::System.DateTime value);
        partial void OnBeginChanged();
        /// <summary>
        /// There are no comments for Property Cycle in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Cycle
        {
            get
            {
                return this._Cycle;
            }
            set
            {
                this.OnCycleChanging(value);
                this._Cycle = value;
                this.OnCycleChanged();
                this.OnPropertyChanged("Cycle");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Cycle;
        partial void OnCycleChanging(int value);
        partial void OnCycleChanged();
        /// <summary>
        /// There are no comments for Property End in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime End
        {
            get
            {
                return this._End;
            }
            set
            {
                this.OnEndChanging(value);
                this._End = value;
                this.OnEndChanged();
                this.OnPropertyChanged("End");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
        /// <summary>
        /// There are no comments for Property EndsWithDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool EndsWithDate
        {
            get
            {
                return this._EndsWithDate;
            }
            set
            {
                this.OnEndsWithDateChanging(value);
                this._EndsWithDate = value;
                this.OnEndsWithDateChanged();
                this.OnPropertyChanged("EndsWithDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _EndsWithDate;
        partial void OnEndsWithDateChanging(bool value);
        partial void OnEndsWithDateChanged();
        /// <summary>
        /// There are no comments for Property IsAllDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsAllDay
        {
            get
            {
                return this._IsAllDay;
            }
            set
            {
                this.OnIsAllDayChanging(value);
                this._IsAllDay = value;
                this.OnIsAllDayChanged();
                this.OnPropertyChanged("IsAllDay");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsAllDay;
        partial void OnIsAllDayChanging(bool value);
        partial void OnIsAllDayChanged();
        /// <summary>
        /// There are no comments for Property IsWeekdayRecurrence in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsWeekdayRecurrence
        {
            get
            {
                return this._IsWeekdayRecurrence;
            }
            set
            {
                this.OnIsWeekdayRecurrenceChanging(value);
                this._IsWeekdayRecurrence = value;
                this.OnIsWeekdayRecurrenceChanged();
                this.OnPropertyChanged("IsWeekdayRecurrence");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsWeekdayRecurrence;
        partial void OnIsWeekdayRecurrenceChanging(bool value);
        partial void OnIsWeekdayRecurrenceChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NumberOfRecurrences in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int NumberOfRecurrences
        {
            get
            {
                return this._NumberOfRecurrences;
            }
            set
            {
                this.OnNumberOfRecurrencesChanging(value);
                this._NumberOfRecurrences = value;
                this.OnNumberOfRecurrencesChanged();
                this.OnPropertyChanged("NumberOfRecurrences");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _NumberOfRecurrences;
        partial void OnNumberOfRecurrencesChanging(int value);
        partial void OnNumberOfRecurrencesChanged();
        /// <summary>
        /// There are no comments for Property RecurrenceInterval in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RecurrenceInterval
        {
            get
            {
                return this._RecurrenceInterval;
            }
            set
            {
                this.OnRecurrenceIntervalChanging(value);
                this._RecurrenceInterval = value;
                this.OnRecurrenceIntervalChanged();
                this.OnPropertyChanged("RecurrenceInterval");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RecurrenceInterval;
        partial void OnRecurrenceIntervalChanging(int value);
        partial void OnRecurrenceIntervalChanged();
        /// <summary>
        /// There are no comments for Property Repeat in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Repeat
        {
            get
            {
                return this._Repeat;
            }
            set
            {
                this.OnRepeatChanging(value);
                this._Repeat = value;
                this.OnRepeatChanged();
                this.OnPropertyChanged("Repeat");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Repeat;
        partial void OnRepeatChanging(bool value);
        partial void OnRepeatChanged();
        /// <summary>
        /// There are no comments for Property RepeatUntilDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime RepeatUntilDate
        {
            get
            {
                return this._RepeatUntilDate;
            }
            set
            {
                this.OnRepeatUntilDateChanging(value);
                this._RepeatUntilDate = value;
                this.OnRepeatUntilDateChanged();
                this.OnPropertyChanged("RepeatUntilDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _RepeatUntilDate;
        partial void OnRepeatUntilDateChanging(global::System.DateTime value);
        partial void OnRepeatUntilDateChanged();
        /// <summary>
        /// There are no comments for SeriesColor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public SeriesColor SeriesColor
        {
            get
            {
                return this._SeriesColor;
            }
            set
            {
                this._SeriesColor = value;
                this.OnPropertyChanged("SeriesColor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private SeriesColor _SeriesColor;
        /// <summary>
        /// There are no comments for WeekDays in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<DayOfWeek> WeekDays
        {
            get
            {
                return this._WeekDays;
            }
            set
            {
                this._WeekDays = value;
                this.OnPropertyChanged("WeekDays");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<DayOfWeek> _WeekDays = new global::System.Data.Services.Client.DataServiceCollection<DayOfWeek>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.SeriesColor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("SeriesColors")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class SeriesColor : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SeriesColor object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="b">Initial value of B.</param>
        /// <param name="g">Initial value of G.</param>
        /// <param name="r">Initial value of R.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SeriesColor CreateSeriesColor(int ID, byte b, byte g, byte r)
        {
            SeriesColor seriesColor = new SeriesColor();
            seriesColor.Id = ID;
            seriesColor.B = b;
            seriesColor.G = g;
            seriesColor.R = r;
            return seriesColor;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property B in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte B
        {
            get
            {
                return this._B;
            }
            set
            {
                this.OnBChanging(value);
                this._B = value;
                this.OnBChanged();
                this.OnPropertyChanged("B");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _B;
        partial void OnBChanging(byte value);
        partial void OnBChanged();
        /// <summary>
        /// There are no comments for Property G in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte G
        {
            get
            {
                return this._G;
            }
            set
            {
                this.OnGChanging(value);
                this._G = value;
                this.OnGChanged();
                this.OnPropertyChanged("G");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _G;
        partial void OnGChanging(byte value);
        partial void OnGChanged();
        /// <summary>
        /// There are no comments for Property R in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte R
        {
            get
            {
                return this._R;
            }
            set
            {
                this.OnRChanging(value);
                this._R = value;
                this.OnRChanged();
                this.OnPropertyChanged("R");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte _R;
        partial void OnRChanging(byte value);
        partial void OnRChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.DayOfWeek in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DayOfWeeks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DayOfWeek : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DayOfWeek object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="weekDay">Initial value of WeekDay.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DayOfWeek CreateDayOfWeek(int ID, int weekDay)
        {
            DayOfWeek dayOfWeek = new DayOfWeek();
            dayOfWeek.Id = ID;
            dayOfWeek.WeekDay = weekDay;
            return dayOfWeek;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property WeekDay in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int WeekDay
        {
            get
            {
                return this._WeekDay;
            }
            set
            {
                this.OnWeekDayChanging(value);
                this._WeekDay = value;
                this.OnWeekDayChanged();
                this.OnPropertyChanged("WeekDay");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _WeekDay;
        partial void OnWeekDayChanging(int value);
        partial void OnWeekDayChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.ScheduledTask in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ScheduledTasks")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class ScheduledTask : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ScheduledTask object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="progress">Initial value of Progress.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ScheduledTask CreateScheduledTask(int ID, float progress)
        {
            ScheduledTask scheduledTask = new ScheduledTask();
            scheduledTask.Id = ID;
            scheduledTask.Progress = progress;
            return scheduledTask;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Progress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public float Progress
        {
            get
            {
                return this._Progress;
            }
            set
            {
                this.OnProgressChanging(value);
                this._Progress = value;
                this.OnProgressChanged();
                this.OnPropertyChanged("Progress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private float _Progress;
        partial void OnProgressChanging(float value);
        partial void OnProgressChanged();
        /// <summary>
        /// There are no comments for AppointmentResponsibleSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ResponsibleSubject AppointmentResponsibleSubject
        {
            get
            {
                return this._AppointmentResponsibleSubject;
            }
            set
            {
                this._AppointmentResponsibleSubject = value;
                this.OnPropertyChanged("AppointmentResponsibleSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ResponsibleSubject _AppointmentResponsibleSubject;
        /// <summary>
        /// There are no comments for DueDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Appointment DueDate
        {
            get
            {
                return this._DueDate;
            }
            set
            {
                this._DueDate = value;
                this.OnPropertyChanged("DueDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Appointment _DueDate;
        /// <summary>
        /// There are no comments for EntryDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Appointment EntryDate
        {
            get
            {
                return this._EntryDate;
            }
            set
            {
                this._EntryDate = value;
                this.OnPropertyChanged("EntryDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Appointment _EntryDate;
        /// <summary>
        /// There are no comments for EntryResponsibleSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ResponsibleSubject EntryResponsibleSubject
        {
            get
            {
                return this._EntryResponsibleSubject;
            }
            set
            {
                this._EntryResponsibleSubject = value;
                this.OnPropertyChanged("EntryResponsibleSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private ResponsibleSubject _EntryResponsibleSubject;
        /// <summary>
        /// There are no comments for RelatedSeries in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Series RelatedSeries
        {
            get
            {
                return this._RelatedSeries;
            }
            set
            {
                this._RelatedSeries = value;
                this.OnPropertyChanged("RelatedSeries");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Series _RelatedSeries;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MeterReading in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeterReading : ScheduledTask
    {
        /// <summary>
        /// Create a new MeterReading object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="progress">Initial value of Progress.</param>
        /// <param name="counterReading">Initial value of CounterReading.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeterReading CreateMeterReading(int ID, float progress, double counterReading)
        {
            MeterReading meterReading = new MeterReading();
            meterReading.Id = ID;
            meterReading.Progress = progress;
            meterReading.CounterReading = counterReading;
            return meterReading;
        }
        /// <summary>
        /// There are no comments for Property CounterReading in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double CounterReading
        {
            get
            {
                return this._CounterReading;
            }
            set
            {
                this.OnCounterReadingChanging(value);
                this._CounterReading = value;
                this.OnCounterReadingChanged();
                this.OnPropertyChanged("CounterReading");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _CounterReading;
        partial void OnCounterReadingChanging(double value);
        partial void OnCounterReadingChanged();
        /// <summary>
        /// There are no comments for ReadingMeter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Meter ReadingMeter
        {
            get
            {
                return this._ReadingMeter;
            }
            set
            {
                this._ReadingMeter = value;
                this.OnPropertyChanged("ReadingMeter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Meter _ReadingMeter;
    }
}
