//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ork.CarbonFootprint.PositionDataProvider {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullyQualifiedCarData", Namespace="http://schemas.datacontract.org/2004/07/OpenResKit.CarbonFootprint.Positions")]
    [System.SerializableAttribute()]
    public partial class FullyQualifiedCarData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CO2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateOfChangeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double EmissionsCOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> EmissionsHCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> EmissionsHCNOxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> EmissionsNOxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> EmissionsParticulatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EngineCapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EuroStandardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FuelCostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImperialCombinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImperialExtraUrbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImperialUrbanColdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MetricCombinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MetricExtraUrbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MetricUrbanColdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NoiseLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransmissionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CO2 {
            get {
                return this.CO2Field;
            }
            set {
                if ((this.CO2Field.Equals(value) != true)) {
                    this.CO2Field = value;
                    this.RaisePropertyChanged("CO2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateOfChange {
            get {
                return this.DateOfChangeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateOfChangeField, value) != true)) {
                    this.DateOfChangeField = value;
                    this.RaisePropertyChanged("DateOfChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double EmissionsCO {
            get {
                return this.EmissionsCOField;
            }
            set {
                if ((this.EmissionsCOField.Equals(value) != true)) {
                    this.EmissionsCOField = value;
                    this.RaisePropertyChanged("EmissionsCO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EmissionsHC {
            get {
                return this.EmissionsHCField;
            }
            set {
                if ((this.EmissionsHCField.Equals(value) != true)) {
                    this.EmissionsHCField = value;
                    this.RaisePropertyChanged("EmissionsHC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EmissionsHCNOx {
            get {
                return this.EmissionsHCNOxField;
            }
            set {
                if ((this.EmissionsHCNOxField.Equals(value) != true)) {
                    this.EmissionsHCNOxField = value;
                    this.RaisePropertyChanged("EmissionsHCNOx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EmissionsNOx {
            get {
                return this.EmissionsNOxField;
            }
            set {
                if ((this.EmissionsNOxField.Equals(value) != true)) {
                    this.EmissionsNOxField = value;
                    this.RaisePropertyChanged("EmissionsNOx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> EmissionsParticulates {
            get {
                return this.EmissionsParticulatesField;
            }
            set {
                if ((this.EmissionsParticulatesField.Equals(value) != true)) {
                    this.EmissionsParticulatesField = value;
                    this.RaisePropertyChanged("EmissionsParticulates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EngineCapacity {
            get {
                return this.EngineCapacityField;
            }
            set {
                if ((this.EngineCapacityField.Equals(value) != true)) {
                    this.EngineCapacityField = value;
                    this.RaisePropertyChanged("EngineCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EuroStandard {
            get {
                return this.EuroStandardField;
            }
            set {
                if ((this.EuroStandardField.Equals(value) != true)) {
                    this.EuroStandardField = value;
                    this.RaisePropertyChanged("EuroStandard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FuelCost {
            get {
                return this.FuelCostField;
            }
            set {
                if ((this.FuelCostField.Equals(value) != true)) {
                    this.FuelCostField = value;
                    this.RaisePropertyChanged("FuelCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelType {
            get {
                return this.FuelTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FuelTypeField, value) != true)) {
                    this.FuelTypeField = value;
                    this.RaisePropertyChanged("FuelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImperialCombined {
            get {
                return this.ImperialCombinedField;
            }
            set {
                if ((this.ImperialCombinedField.Equals(value) != true)) {
                    this.ImperialCombinedField = value;
                    this.RaisePropertyChanged("ImperialCombined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImperialExtraUrban {
            get {
                return this.ImperialExtraUrbanField;
            }
            set {
                if ((this.ImperialExtraUrbanField.Equals(value) != true)) {
                    this.ImperialExtraUrbanField = value;
                    this.RaisePropertyChanged("ImperialExtraUrban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ImperialUrbanCold {
            get {
                return this.ImperialUrbanColdField;
            }
            set {
                if ((this.ImperialUrbanColdField.Equals(value) != true)) {
                    this.ImperialUrbanColdField = value;
                    this.RaisePropertyChanged("ImperialUrbanCold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer {
            get {
                return this.ManufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManufacturerField, value) != true)) {
                    this.ManufacturerField = value;
                    this.RaisePropertyChanged("Manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MetricCombined {
            get {
                return this.MetricCombinedField;
            }
            set {
                if ((this.MetricCombinedField.Equals(value) != true)) {
                    this.MetricCombinedField = value;
                    this.RaisePropertyChanged("MetricCombined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MetricExtraUrban {
            get {
                return this.MetricExtraUrbanField;
            }
            set {
                if ((this.MetricExtraUrbanField.Equals(value) != true)) {
                    this.MetricExtraUrbanField = value;
                    this.RaisePropertyChanged("MetricExtraUrban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MetricUrbanCold {
            get {
                return this.MetricUrbanColdField;
            }
            set {
                if ((this.MetricUrbanColdField.Equals(value) != true)) {
                    this.MetricUrbanColdField = value;
                    this.RaisePropertyChanged("MetricUrbanCold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NoiseLevel {
            get {
                return this.NoiseLevelField;
            }
            set {
                if ((this.NoiseLevelField.Equals(value) != true)) {
                    this.NoiseLevelField = value;
                    this.RaisePropertyChanged("NoiseLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Transmission {
            get {
                return this.TransmissionField;
            }
            set {
                if ((object.ReferenceEquals(this.TransmissionField, value) != true)) {
                    this.TransmissionField = value;
                    this.RaisePropertyChanged("Transmission");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GlobalAirport", Namespace="http://schemas.datacontract.org/2004/07/OpenResKit.CarbonFootprint.Positions")]
    [System.SerializableAttribute()]
    public partial class GlobalAirport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string continentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> elevation_ftField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gps_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string home_linkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iata_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string identField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iso_countryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iso_regionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string keywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitude_degField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string local_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitude_degField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string municipalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string scheduled_serviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string wikipedia_linkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string continent {
            get {
                return this.continentField;
            }
            set {
                if ((object.ReferenceEquals(this.continentField, value) != true)) {
                    this.continentField = value;
                    this.RaisePropertyChanged("continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> elevation_ft {
            get {
                return this.elevation_ftField;
            }
            set {
                if ((this.elevation_ftField.Equals(value) != true)) {
                    this.elevation_ftField = value;
                    this.RaisePropertyChanged("elevation_ft");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gps_code {
            get {
                return this.gps_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.gps_codeField, value) != true)) {
                    this.gps_codeField = value;
                    this.RaisePropertyChanged("gps_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string home_link {
            get {
                return this.home_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.home_linkField, value) != true)) {
                    this.home_linkField = value;
                    this.RaisePropertyChanged("home_link");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iata_code {
            get {
                return this.iata_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.iata_codeField, value) != true)) {
                    this.iata_codeField = value;
                    this.RaisePropertyChanged("iata_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ident {
            get {
                return this.identField;
            }
            set {
                if ((object.ReferenceEquals(this.identField, value) != true)) {
                    this.identField = value;
                    this.RaisePropertyChanged("ident");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iso_country {
            get {
                return this.iso_countryField;
            }
            set {
                if ((object.ReferenceEquals(this.iso_countryField, value) != true)) {
                    this.iso_countryField = value;
                    this.RaisePropertyChanged("iso_country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iso_region {
            get {
                return this.iso_regionField;
            }
            set {
                if ((object.ReferenceEquals(this.iso_regionField, value) != true)) {
                    this.iso_regionField = value;
                    this.RaisePropertyChanged("iso_region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string keywords {
            get {
                return this.keywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.keywordsField, value) != true)) {
                    this.keywordsField = value;
                    this.RaisePropertyChanged("keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude_deg {
            get {
                return this.latitude_degField;
            }
            set {
                if ((this.latitude_degField.Equals(value) != true)) {
                    this.latitude_degField = value;
                    this.RaisePropertyChanged("latitude_deg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string local_code {
            get {
                return this.local_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.local_codeField, value) != true)) {
                    this.local_codeField = value;
                    this.RaisePropertyChanged("local_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude_deg {
            get {
                return this.longitude_degField;
            }
            set {
                if ((this.longitude_degField.Equals(value) != true)) {
                    this.longitude_degField = value;
                    this.RaisePropertyChanged("longitude_deg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string municipality {
            get {
                return this.municipalityField;
            }
            set {
                if ((object.ReferenceEquals(this.municipalityField, value) != true)) {
                    this.municipalityField = value;
                    this.RaisePropertyChanged("municipality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string scheduled_service {
            get {
                return this.scheduled_serviceField;
            }
            set {
                if ((object.ReferenceEquals(this.scheduled_serviceField, value) != true)) {
                    this.scheduled_serviceField = value;
                    this.RaisePropertyChanged("scheduled_service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string wikipedia_link {
            get {
                return this.wikipedia_linkField;
            }
            set {
                if ((object.ReferenceEquals(this.wikipedia_linkField, value) != true)) {
                    this.wikipedia_linkField = value;
                    this.RaisePropertyChanged("wikipedia_link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PositionDataProvider.PositionDataContext")]
    public interface PositionDataContext {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PositionDataContext/GetFullyQualifiedCarData", ReplyAction="http://tempuri.org/PositionDataContext/GetFullyQualifiedCarDataResponse")]
        Ork.CarbonFootprint.PositionDataProvider.FullyQualifiedCarData[] GetFullyQualifiedCarData();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PositionDataContext/GetFullyQualifiedCarData", ReplyAction="http://tempuri.org/PositionDataContext/GetFullyQualifiedCarDataResponse")]
        System.IAsyncResult BeginGetFullyQualifiedCarData(System.AsyncCallback callback, object asyncState);
        
        Ork.CarbonFootprint.PositionDataProvider.FullyQualifiedCarData[] EndGetFullyQualifiedCarData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PositionDataContext/GetAirportData", ReplyAction="http://tempuri.org/PositionDataContext/GetAirportDataResponse")]
        Ork.CarbonFootprint.PositionDataProvider.GlobalAirport[] GetAirportData();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/PositionDataContext/GetAirportData", ReplyAction="http://tempuri.org/PositionDataContext/GetAirportDataResponse")]
        System.IAsyncResult BeginGetAirportData(System.AsyncCallback callback, object asyncState);
        
        Ork.CarbonFootprint.PositionDataProvider.GlobalAirport[] EndGetAirportData(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PositionDataContextChannel : Ork.CarbonFootprint.PositionDataProvider.PositionDataContext, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetFullyQualifiedCarDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetFullyQualifiedCarDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Ork.CarbonFootprint.PositionDataProvider.FullyQualifiedCarData[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Ork.CarbonFootprint.PositionDataProvider.FullyQualifiedCarData[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAirportDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAirportDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Ork.CarbonFootprint.PositionDataProvider.GlobalAirport[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Ork.CarbonFootprint.PositionDataProvider.GlobalAirport[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PositionDataContextClient : System.ServiceModel.ClientBase<Ork.CarbonFootprint.PositionDataProvider.PositionDataContext>, Ork.CarbonFootprint.PositionDataProvider.PositionDataContext {
        
        private BeginOperationDelegate onBeginGetFullyQualifiedCarDataDelegate;
        
        private EndOperationDelegate onEndGetFullyQualifiedCarDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetFullyQualifiedCarDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAirportDataDelegate;
        
        private EndOperationDelegate onEndGetAirportDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetAirportDataCompletedDelegate;
        
        public PositionDataContextClient() {
        }
        
        public PositionDataContextClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PositionDataContextClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositionDataContextClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PositionDataContextClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetFullyQualifiedCarDataCompletedEventArgs> GetFullyQualifiedCarDataCompleted;
        
        public event System.EventHandler<GetAirportDataCompletedEventArgs> GetAirportDataCompleted;
        
        public Ork.CarbonFootprint.PositionDataProvider.FullyQualifiedCarData[] GetFullyQualifiedCarData() {
            return base.Channel.GetFullyQualifiedCarData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetFullyQualifiedCarData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetFullyQualifiedCarData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Ork.CarbonFootprint.PositionDataProvider.FullyQualifiedCarData[] EndGetFullyQualifiedCarData(System.IAsyncResult result) {
            return base.Channel.EndGetFullyQualifiedCarData(result);
        }
        
        private System.IAsyncResult OnBeginGetFullyQualifiedCarData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetFullyQualifiedCarData(callback, asyncState);
        }
        
        private object[] OnEndGetFullyQualifiedCarData(System.IAsyncResult result) {
            Ork.CarbonFootprint.PositionDataProvider.FullyQualifiedCarData[] retVal = this.EndGetFullyQualifiedCarData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetFullyQualifiedCarDataCompleted(object state) {
            if ((this.GetFullyQualifiedCarDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetFullyQualifiedCarDataCompleted(this, new GetFullyQualifiedCarDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetFullyQualifiedCarDataAsync() {
            this.GetFullyQualifiedCarDataAsync(null);
        }
        
        public void GetFullyQualifiedCarDataAsync(object userState) {
            if ((this.onBeginGetFullyQualifiedCarDataDelegate == null)) {
                this.onBeginGetFullyQualifiedCarDataDelegate = new BeginOperationDelegate(this.OnBeginGetFullyQualifiedCarData);
            }
            if ((this.onEndGetFullyQualifiedCarDataDelegate == null)) {
                this.onEndGetFullyQualifiedCarDataDelegate = new EndOperationDelegate(this.OnEndGetFullyQualifiedCarData);
            }
            if ((this.onGetFullyQualifiedCarDataCompletedDelegate == null)) {
                this.onGetFullyQualifiedCarDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetFullyQualifiedCarDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetFullyQualifiedCarDataDelegate, null, this.onEndGetFullyQualifiedCarDataDelegate, this.onGetFullyQualifiedCarDataCompletedDelegate, userState);
        }
        
        public Ork.CarbonFootprint.PositionDataProvider.GlobalAirport[] GetAirportData() {
            return base.Channel.GetAirportData();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAirportData(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAirportData(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Ork.CarbonFootprint.PositionDataProvider.GlobalAirport[] EndGetAirportData(System.IAsyncResult result) {
            return base.Channel.EndGetAirportData(result);
        }
        
        private System.IAsyncResult OnBeginGetAirportData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAirportData(callback, asyncState);
        }
        
        private object[] OnEndGetAirportData(System.IAsyncResult result) {
            Ork.CarbonFootprint.PositionDataProvider.GlobalAirport[] retVal = this.EndGetAirportData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAirportDataCompleted(object state) {
            if ((this.GetAirportDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAirportDataCompleted(this, new GetAirportDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAirportDataAsync() {
            this.GetAirportDataAsync(null);
        }
        
        public void GetAirportDataAsync(object userState) {
            if ((this.onBeginGetAirportDataDelegate == null)) {
                this.onBeginGetAirportDataDelegate = new BeginOperationDelegate(this.OnBeginGetAirportData);
            }
            if ((this.onEndGetAirportDataDelegate == null)) {
                this.onEndGetAirportDataDelegate = new EndOperationDelegate(this.OnEndGetAirportData);
            }
            if ((this.onGetAirportDataCompletedDelegate == null)) {
                this.onGetAirportDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAirportDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetAirportDataDelegate, null, this.onEndGetAirportDataDelegate, this.onGetAirportDataCompletedDelegate, userState);
        }
    }
}
