//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ork.Waste.AVVCatalog {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvvWasteType", Namespace="http://schemas.datacontract.org/2004/07/OpenResKit.Waste")]
    [System.SerializableAttribute()]
    public partial class AvvWasteType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AVVCatalog.AVVProviderService")]
    public interface AVVProviderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AVVProviderService/GetAvvCatalogue", ReplyAction="http://tempuri.org/AVVProviderService/GetAvvCatalogueResponse")]
        Ork.Waste.AVVCatalog.AvvWasteType[] GetAvvCatalogue();
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AVVProviderService/GetAvvCatalogue", ReplyAction="http://tempuri.org/AVVProviderService/GetAvvCatalogueResponse")]
        System.IAsyncResult BeginGetAvvCatalogue(System.AsyncCallback callback, object asyncState);
        
        Ork.Waste.AVVCatalog.AvvWasteType[] EndGetAvvCatalogue(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AVVProviderServiceChannel : Ork.Waste.AVVCatalog.AVVProviderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAvvCatalogueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAvvCatalogueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Ork.Waste.AVVCatalog.AvvWasteType[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Ork.Waste.AVVCatalog.AvvWasteType[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AVVProviderServiceClient : System.ServiceModel.ClientBase<Ork.Waste.AVVCatalog.AVVProviderService>, Ork.Waste.AVVCatalog.AVVProviderService {
        
        private BeginOperationDelegate onBeginGetAvvCatalogueDelegate;
        
        private EndOperationDelegate onEndGetAvvCatalogueDelegate;
        
        private System.Threading.SendOrPostCallback onGetAvvCatalogueCompletedDelegate;
        
        public AVVProviderServiceClient() {
        }
        
        public AVVProviderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AVVProviderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AVVProviderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AVVProviderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetAvvCatalogueCompletedEventArgs> GetAvvCatalogueCompleted;
        
        public Ork.Waste.AVVCatalog.AvvWasteType[] GetAvvCatalogue() {
            return base.Channel.GetAvvCatalogue();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAvvCatalogue(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAvvCatalogue(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Ork.Waste.AVVCatalog.AvvWasteType[] EndGetAvvCatalogue(System.IAsyncResult result) {
            return base.Channel.EndGetAvvCatalogue(result);
        }
        
        private System.IAsyncResult OnBeginGetAvvCatalogue(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetAvvCatalogue(callback, asyncState);
        }
        
        private object[] OnEndGetAvvCatalogue(System.IAsyncResult result) {
            Ork.Waste.AVVCatalog.AvvWasteType[] retVal = this.EndGetAvvCatalogue(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAvvCatalogueCompleted(object state) {
            if ((this.GetAvvCatalogueCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAvvCatalogueCompleted(this, new GetAvvCatalogueCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAvvCatalogueAsync() {
            this.GetAvvCatalogueAsync(null);
        }
        
        public void GetAvvCatalogueAsync(object userState) {
            if ((this.onBeginGetAvvCatalogueDelegate == null)) {
                this.onBeginGetAvvCatalogueDelegate = new BeginOperationDelegate(this.OnBeginGetAvvCatalogue);
            }
            if ((this.onEndGetAvvCatalogueDelegate == null)) {
                this.onEndGetAvvCatalogueDelegate = new EndOperationDelegate(this.OnEndGetAvvCatalogue);
            }
            if ((this.onGetAvvCatalogueCompletedDelegate == null)) {
                this.onGetAvvCatalogueCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAvvCatalogueCompleted);
            }
            base.InvokeAsync(this.onBeginGetAvvCatalogueDelegate, null, this.onEndGetAvvCatalogueDelegate, this.onGetAvvCatalogueCompletedDelegate, userState);
        }
    }
}
