//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 27.11.2013 16:21:46
namespace Ork.MeterRelatedElement.DomainModelService
{
    
    /// <summary>
    /// There are no comments for DomainModelContext in the schema.
    /// </summary>
    public partial class DomainModelContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DomainModelContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DomainModelContext(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("OpenResKit.DomainModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Ork.MeterRelatedElement.DomainModelService", typeName.Substring(22)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Ork.MeterRelatedElement.DomainModelService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("OpenResKit.DomainModel.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Measures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Measure> Measures
        {
            get
            {
                if ((this._Measures == null))
                {
                    this._Measures = base.CreateQuery<Measure>("Measures");
                }
                return this._Measures;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Measure> _Measures;
        /// <summary>
        /// There are no comments for ResponsibleSubjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ResponsibleSubject> ResponsibleSubjects
        {
            get
            {
                if ((this._ResponsibleSubjects == null))
                {
                    this._ResponsibleSubjects = base.CreateQuery<ResponsibleSubject>("ResponsibleSubjects");
                }
                return this._ResponsibleSubjects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ResponsibleSubject> _ResponsibleSubjects;
        /// <summary>
        /// There are no comments for Catalogs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Catalog> Catalogs
        {
            get
            {
                if ((this._Catalogs == null))
                {
                    this._Catalogs = base.CreateQuery<Catalog>("Catalogs");
                }
                return this._Catalogs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Catalog> _Catalogs;
        /// <summary>
        /// There are no comments for Meters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Meter> Meters
        {
            get
            {
                if ((this._Meters == null))
                {
                    this._Meters = base.CreateQuery<Meter>("Meters");
                }
                return this._Meters;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Meter> _Meters;
        /// <summary>
        /// There are no comments for MapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MapPosition> MapPositions
        {
            get
            {
                if ((this._MapPositions == null))
                {
                    this._MapPositions = base.CreateQuery<MapPosition>("MapPositions");
                }
                return this._MapPositions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MapPosition> _MapPositions;
        /// <summary>
        /// There are no comments for Maps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Map> Maps
        {
            get
            {
                if ((this._Maps == null))
                {
                    this._Maps = base.CreateQuery<Map>("Maps");
                }
                return this._Maps;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Map> _Maps;
        /// <summary>
        /// There are no comments for MapSources in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MapSource> MapSources
        {
            get
            {
                if ((this._MapSources == null))
                {
                    this._MapSources = base.CreateQuery<MapSource>("MapSources");
                }
                return this._MapSources;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MapSource> _MapSources;
        /// <summary>
        /// There are no comments for MeterRelatedElements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MeterRelatedElement> MeterRelatedElements
        {
            get
            {
                if ((this._MeterRelatedElements == null))
                {
                    this._MeterRelatedElements = base.CreateQuery<MeterRelatedElement>("MeterRelatedElements");
                }
                return this._MeterRelatedElements;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MeterRelatedElement> _MeterRelatedElements;
        /// <summary>
        /// There are no comments for Measures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeasures(Measure measure)
        {
            base.AddObject("Measures", measure);
        }
        /// <summary>
        /// There are no comments for ResponsibleSubjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToResponsibleSubjects(ResponsibleSubject responsibleSubject)
        {
            base.AddObject("ResponsibleSubjects", responsibleSubject);
        }
        /// <summary>
        /// There are no comments for Catalogs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCatalogs(Catalog catalog)
        {
            base.AddObject("Catalogs", catalog);
        }
        /// <summary>
        /// There are no comments for Meters in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeters(Meter meter)
        {
            base.AddObject("Meters", meter);
        }
        /// <summary>
        /// There are no comments for MapPositions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMapPositions(MapPosition mapPosition)
        {
            base.AddObject("MapPositions", mapPosition);
        }
        /// <summary>
        /// There are no comments for Maps in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMaps(Map map)
        {
            base.AddObject("Maps", map);
        }
        /// <summary>
        /// There are no comments for MapSources in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMapSources(MapSource mapSource)
        {
            base.AddObject("MapSources", mapSource);
        }
        /// <summary>
        /// There are no comments for MeterRelatedElements in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMeterRelatedElements(MeterRelatedElement meterRelatedElement)
        {
            base.AddObject("MeterRelatedElements", meterRelatedElement);
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.Measure" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Measures")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Measure: global::System.ComponentModel.INotifyPropertyChanged
    {
      /// <summary>
      /// Erstellt ein neues Measure-Objekt.
      /// </summary>
      /// <param name="ID">Anfangswert von Id.</param>
      /// <param name="dueDate">Anfangswert von DueDate.</param>
      /// <param name="creationDate">Anfangswert von CreationDate.</param>
      /// <param name="status">Anfangswert von Status.</param>
      /// <param name="priority">Anfangswert von Priority.</param>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public static Measure CreateMeasure(int ID, global::System.DateTime dueDate, global::System.DateTime creationDate, int status, int priority)
      {
        Measure measure = new Measure();
        measure.Id = ID;
        measure.DueDate = dueDate;
        measure.CreationDate = creationDate;
        measure.Status = status;
        measure.Priority = priority;
        return measure;
      }
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public int Id
      {
        get
        {
          return this._Id;
        }
        set
        {
          this.OnIdChanging(value);
          this._Id = value;
          this.OnIdChanged();
          this.OnPropertyChanged("Id");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private int _Id;
      partial void OnIdChanging(int value);
      partial void OnIdChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public string Name
      {
        get
        {
          return this._Name;
        }
        set
        {
          this.OnNameChanging(value);
          this._Name = value;
          this.OnNameChanged();
          this.OnPropertyChanged("Name");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private string _Name;
      partial void OnNameChanging(string value);
      partial void OnNameChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Description" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public string Description
      {
        get
        {
          return this._Description;
        }
        set
        {
          this.OnDescriptionChanging(value);
          this._Description = value;
          this.OnDescriptionChanged();
          this.OnPropertyChanged("Description");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private string _Description;
      partial void OnDescriptionChanging(string value);
      partial void OnDescriptionChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Evaluation" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public string Evaluation
      {
        get
        {
          return this._Evaluation;
        }
        set
        {
          this.OnEvaluationChanging(value);
          this._Evaluation = value;
          this.OnEvaluationChanged();
          this.OnPropertyChanged("Evaluation");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private string _Evaluation;
      partial void OnEvaluationChanging(string value);
      partial void OnEvaluationChanged();
      /// <summary>
      /// There are no comments for Property EvaluationRating in the schema.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public double EvaluationRating
      {
        get
        {
          return this._EvaluationRating;
        }
        set
        {
          this.OnEvaluationRatingChanging(value);
          this._EvaluationRating = value;
          this.OnEvaluationRatingChanged();
          this.OnPropertyChanged("EvaluationRating");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private double _EvaluationRating;
      partial void OnEvaluationRatingChanging(double value);
      partial void OnEvaluationRatingChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "EntryDate" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public global::System.Nullable<global::System.DateTime> EntryDate
      {
        get
        {
          return this._EntryDate;
        }
        set
        {
          this.OnEntryDateChanging(value);
          this._EntryDate = value;
          this.OnEntryDateChanged();
          this.OnPropertyChanged("EntryDate");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private global::System.Nullable<global::System.DateTime> _EntryDate;
      partial void OnEntryDateChanging(global::System.Nullable<global::System.DateTime> value);
      partial void OnEntryDateChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "DueDate" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public global::System.DateTime DueDate
      {
        get
        {
          return this._DueDate;
        }
        set
        {
          this.OnDueDateChanging(value);
          this._DueDate = value;
          this.OnDueDateChanged();
          this.OnPropertyChanged("DueDate");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private global::System.DateTime _DueDate;
      partial void OnDueDateChanging(global::System.DateTime value);
      partial void OnDueDateChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "CreationDate" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public global::System.DateTime CreationDate
      {
        get
        {
          return this._CreationDate;
        }
        set
        {
          this.OnCreationDateChanging(value);
          this._CreationDate = value;
          this.OnCreationDateChanged();
          this.OnPropertyChanged("CreationDate");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private global::System.DateTime _CreationDate;
      partial void OnCreationDateChanging(global::System.DateTime value);
      partial void OnCreationDateChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Status" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public int Status
      {
        get
        {
          return this._Status;
        }
        set
        {
          this.OnStatusChanging(value);
          this._Status = value;
          this.OnStatusChanged();
          this.OnPropertyChanged("Status");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private int _Status;
      partial void OnStatusChanging(int value);
      partial void OnStatusChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Priority" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public int Priority
      {
        get
        {
          return this._Priority;
        }
        set
        {
          this.OnPriorityChanging(value);
          this._Priority = value;
          this.OnPriorityChanged();
          this.OnPropertyChanged("Priority");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private int _Priority;
      partial void OnPriorityChanging(int value);
      partial void OnPriorityChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für "ResponsibleSubject" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public ResponsibleSubject ResponsibleSubject
      {
        get
        {
          return this._ResponsibleSubject;
        }
        set
        {
          this._ResponsibleSubject = value;
          this.OnPropertyChanged("ResponsibleSubject");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private ResponsibleSubject _ResponsibleSubject;
      /// <summary>
      /// Im Schema sind keine Kommentare für "MeasureImageSource" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public MeasureImageSource MeasureImageSource
      {
        get
        {
          return this._MeasureImageSource;
        }
        set
        {
          this._MeasureImageSource = value;
          this.OnPropertyChanged("MeasureImageSource");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private MeasureImageSource _MeasureImageSource;
      /// <summary>
      /// Im Schema sind keine Kommentare für "AttachedDocuments" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public global::System.Data.Services.Client.DataServiceCollection<Document> AttachedDocuments
      {
        get
        {
          return this._AttachedDocuments;
        }
        set
        {
          this._AttachedDocuments = value;
          this.OnPropertyChanged("AttachedDocuments");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private global::System.Data.Services.Client.DataServiceCollection<Document> _AttachedDocuments = new global::System.Data.Services.Client.DataServiceCollection<Document>(null, global::System.Data.Services.Client.TrackingMode.None);
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      protected virtual void OnPropertyChanged(string property)
      {
        if ((this.PropertyChanged != null))
        {
          this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
        }
      }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.ResponsibleSubject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ResponsibleSubjects")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public abstract partial class ResponsibleSubject : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Employee in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Employee : ResponsibleSubject
    {
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Employee CreateEmployee(int ID)
        {
            Employee employee = new Employee();
            employee.Id = ID;
            return employee;
        }
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Groups in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup> Groups
        {
            get
            {
                return this._Groups;
            }
            set
            {
                this._Groups = value;
                this.OnPropertyChanged("Groups");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup> _Groups = new global::System.Data.Services.Client.DataServiceCollection<EmployeeGroup>(null, global::System.Data.Services.Client.TrackingMode.None);
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.EmployeeGroup in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class EmployeeGroup : ResponsibleSubject
    {
        /// <summary>
        /// Create a new EmployeeGroup object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static EmployeeGroup CreateEmployeeGroup(int ID)
        {
            EmployeeGroup employeeGroup = new EmployeeGroup();
            employeeGroup.Id = ID;
            return employeeGroup;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.MeasureImageSource" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeasureImageSources")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeasureImageSource: global::System.ComponentModel.INotifyPropertyChanged
    {
      /// <summary>
      /// Erstellt ein neues MeasureImageSource-Objekt.
      /// </summary>
      /// <param name="ID">Anfangswert von Id.</param>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public static MeasureImageSource CreateMeasureImageSource(int ID)
      {
        MeasureImageSource imageSource = new MeasureImageSource();
        imageSource.Id = ID;
        return imageSource;
      }
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public int Id
      {
        get
        {
          return this._Id;
        }
        set
        {
          this.OnIdChanging(value);
          this._Id = value;
          this.OnIdChanged();
          this.OnPropertyChanged("Id");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private int _Id;
      partial void OnIdChanging(int value);
      partial void OnIdChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "BinarySource" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public byte[] BinarySource
      {
        get
        {
          if ((this._BinarySource != null))
          {
            return ((byte[]) (this._BinarySource.Clone()));
          }
          else
          {
            return null;
          }
        }
        set
        {
          this.OnBinarySourceChanging(value);
          this._BinarySource = value;
          this.OnBinarySourceChanged();
          this.OnPropertyChanged("BinarySource");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private byte[] _BinarySource;
      partial void OnBinarySourceChanging(byte[] value);
      partial void OnBinarySourceChanged();
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      protected virtual void OnPropertyChanged(string property)
      {
        if ((this.PropertyChanged != null))
        {
          this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
        }
      }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.Document" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Documents")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Document: global::System.ComponentModel.INotifyPropertyChanged
    {
      /// <summary>
      /// Erstellt ein neues Document-Objekt.
      /// </summary>
      /// <param name="ID">Anfangswert von Id.</param>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public static Document CreateDocument(int ID)
      {
        Document document = new Document();
        document.Id = ID;
        return document;
      }
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public int Id
      {
        get
        {
          return this._Id;
        }
        set
        {
          this.OnIdChanging(value);
          this._Id = value;
          this.OnIdChanged();
          this.OnPropertyChanged("Id");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private int _Id;
      partial void OnIdChanging(int value);
      partial void OnIdChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public string Name
      {
        get
        {
          return this._Name;
        }
        set
        {
          this.OnNameChanging(value);
          this._Name = value;
          this.OnNameChanged();
          this.OnPropertyChanged("Name");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private string _Name;
      partial void OnNameChanging(string value);
      partial void OnNameChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für "DocumentSource" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public DocumentSource DocumentSource
      {
        get
        {
          return this._DocumentSource;
        }
        set
        {
          this._DocumentSource = value;
          this.OnPropertyChanged("DocumentSource");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private DocumentSource _DocumentSource;
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      protected virtual void OnPropertyChanged(string property)
      {
        if ((this.PropertyChanged != null))
        {
          this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
        }
      }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "OpenResKit.DomainModel.DocumentSource" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DocumentSources")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class DocumentSource: global::System.ComponentModel.INotifyPropertyChanged
    {
      /// <summary>
      /// Erstellt ein neues DocumentSource-Objekt.
      /// </summary>
      /// <param name="ID">Anfangswert von Id.</param>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public static DocumentSource CreateDocumentSource(int ID)
      {
        DocumentSource documentSource = new DocumentSource();
        documentSource.Id = ID;
        return documentSource;
      }
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "Id" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public int Id
      {
        get
        {
          return this._Id;
        }
        set
        {
          this.OnIdChanging(value);
          this._Id = value;
          this.OnIdChanged();
          this.OnPropertyChanged("Id");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private int _Id;
      partial void OnIdChanging(int value);
      partial void OnIdChanged();
      /// <summary>
      /// Im Schema sind keine Kommentare für die Eigenschaft "BinarySource" vorhanden.
      /// </summary>
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public byte[] BinarySource
      {
        get
        {
          if ((this._BinarySource != null))
          {
            return ((byte[]) (this._BinarySource.Clone()));
          }
          else
          {
            return null;
          }
        }
        set
        {
          this.OnBinarySourceChanging(value);
          this._BinarySource = value;
          this.OnBinarySourceChanged();
          this.OnPropertyChanged("BinarySource");
        }
      }
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      private byte[] _BinarySource;
      partial void OnBinarySourceChanging(byte[] value);
      partial void OnBinarySourceChanged();
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
      protected virtual void OnPropertyChanged(string property)
      {
        if ((this.PropertyChanged != null))
        {
          this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
        }
      }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Catalog in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Catalogs")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Catalog : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Catalog object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Catalog CreateCatalog(int ID)
        {
            Catalog catalog = new Catalog();
            catalog.Id = ID;
            return catalog;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Measures in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Measure> Measures
        {
            get
            {
                return this._Measures;
            }
            set
            {
                this._Measures = value;
                this.OnPropertyChanged("Measures");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Measure> _Measures = new global::System.Data.Services.Client.DataServiceCollection<Measure>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Meter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Meters")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Meter : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Meter object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="unit">Initial value of Unit.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Meter CreateMeter(int ID, string unit)
        {
            Meter meter = new Meter();
            meter.Id = ID;
            meter.Unit = unit;
            return meter;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Barcode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Barcode
        {
            get
            {
                return this._Barcode;
            }
            set
            {
                this.OnBarcodeChanging(value);
                this._Barcode = value;
                this.OnBarcodeChanged();
                this.OnPropertyChanged("Barcode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Barcode;
        partial void OnBarcodeChanging(string value);
        partial void OnBarcodeChanged();
        /// <summary>
        /// There are no comments for Property Number in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Number
        {
            get
            {
                return this._Number;
            }
            set
            {
                this.OnNumberChanging(value);
                this._Number = value;
                this.OnNumberChanged();
                this.OnPropertyChanged("Number");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Number;
        partial void OnNumberChanging(string value);
        partial void OnNumberChanged();
        /// <summary>
        /// There are no comments for Property Unit in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Unit
        {
            get
            {
                return this._Unit;
            }
            set
            {
                this.OnUnitChanging(value);
                this._Unit = value;
                this.OnUnitChanged();
                this.OnPropertyChanged("Unit");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Unit;
        partial void OnUnitChanging(string value);
        partial void OnUnitChanged();
        /// <summary>
        /// There are no comments for MapPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MapPosition MapPosition
        {
            get
            {
                return this._MapPosition;
            }
            set
            {
                this._MapPosition = value;
                this.OnPropertyChanged("MapPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MapPosition _MapPosition;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MapPosition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MapPositions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MapPosition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MapPosition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="xPosition">Initial value of XPosition.</param>
        /// <param name="yPosition">Initial value of YPosition.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MapPosition CreateMapPosition(int ID, double xPosition, double yPosition)
        {
            MapPosition mapPosition = new MapPosition();
            mapPosition.Id = ID;
            mapPosition.XPosition = xPosition;
            mapPosition.YPosition = yPosition;
            return mapPosition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property XPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double XPosition
        {
            get
            {
                return this._XPosition;
            }
            set
            {
                this.OnXPositionChanging(value);
                this._XPosition = value;
                this.OnXPositionChanged();
                this.OnPropertyChanged("XPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _XPosition;
        partial void OnXPositionChanging(double value);
        partial void OnXPositionChanged();
        /// <summary>
        /// There are no comments for Property YPosition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double YPosition
        {
            get
            {
                return this._YPosition;
            }
            set
            {
                this.OnYPositionChanging(value);
                this._YPosition = value;
                this.OnYPositionChanged();
                this.OnPropertyChanged("YPosition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _YPosition;
        partial void OnYPositionChanging(double value);
        partial void OnYPositionChanged();
        /// <summary>
        /// There are no comments for Map in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Map Map
        {
            get
            {
                return this._Map;
            }
            set
            {
                this._Map = value;
                this.OnPropertyChanged("Map");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Map _Map;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.Map in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Maps")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Map : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Map object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Map CreateMap(int ID)
        {
            Map map = new Map();
            map.Id = ID;
            return map;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for MapSource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MapSource MapSource
        {
            get
            {
                return this._MapSource;
            }
            set
            {
                this._MapSource = value;
                this.OnPropertyChanged("MapSource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private MapSource _MapSource;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MapSource in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MapSources")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MapSource : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MapSource object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MapSource CreateMapSource(int ID)
        {
            MapSource mapSource = new MapSource();
            mapSource.Id = ID;
            return mapSource;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property BinarySource in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] BinarySource
        {
            get
            {
                if ((this._BinarySource != null))
                {
                    return ((byte[])(this._BinarySource.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnBinarySourceChanging(value);
                this._BinarySource = value;
                this.OnBinarySourceChanged();
                this.OnPropertyChanged("BinarySource");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _BinarySource;
        partial void OnBinarySourceChanging(byte[] value);
        partial void OnBinarySourceChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for OpenResKit.DomainModel.MeterRelatedElement in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MeterRelatedElements")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class MeterRelatedElement : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MeterRelatedElement object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MeterRelatedElement CreateMeterRelatedElement(int ID)
        {
            MeterRelatedElement meterRelatedElement = new MeterRelatedElement();
            meterRelatedElement.Id = ID;
            return meterRelatedElement;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Measure in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Measure Measure
        {
            get
            {
                return this._Measure;
            }
            set
            {
                this._Measure = value;
                this.OnPropertyChanged("Measure");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Measure _Measure;
        /// <summary>
        /// There are no comments for Meter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Meter Meter
        {
            get
            {
                return this._Meter;
            }
            set
            {
                this._Meter = value;
                this.OnPropertyChanged("Meter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Meter _Meter;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
